### ISSUE TITLE
Dates events

### ISSUE THREAD

**Issue by ConstanceEYPBE** [young-europe/Members-Platform-bug-reports#130]
The date on an event only shows the first day and not the entire duration ex. https://staging.members.eyp.org/events/bilbao-2021-16th-national-selection-conference-of-eyp-espana

**Comment by mzibara** [comment]
@ConstanceEYPBE 
![image](https://user-images.githubusercontent.com/17460019/138305414-fa317afb-633a-4f99-8467-68fd92bee074.png)

Currently there is the full duration of the event
