### ISSUE TITLE
NC list and filter

### ISSUE THREAD

**Issue by ConstanceEYPBE** [young-europe/Members-Platform-bug-reports#132]
NCs not alphabetical https://staging.members.eyp.org/ncs - possibility to sort by cluster? by oldness? member size? amount of events? Some NCs don’t exist yet (Andorra, Malta..)

**Comment by mzibara** [comment]
NCs will be sorted in alphabetic order, other sorting options will be kept as an idea for the future development

**Comment by mzibara** [comment]
There was an issue with data input - some of the letters was not English - therefore it was appearing at the bottom
