### ISSUE TITLE
Multiple memberships

### ISSUE THREAD

**Issue by SDarius08** [young-europe/Members-Platform-bug-reports#146]
It would be an interesting idea to show every member what NC's memberships they have actives. It will is not so useful in everyday practice but can be just a nice touch for members that have more than 1 membership in the EYP world.

**Comment by valboyko** [comment]
Thank you for your suggestion! Due to the structure of the platform, it is currently not possible to have more than one NC membership. Maybe we will review this down the line, but currently, this is not a priority feature :)
