### ISSUE TITLE
Evaluations do not show role at event

### ISSUE THREAD

**Issue by ghost** [young-europe/Members-Platform-bug-reports#15]
Lars Van Bourgognie - 22/09/2021

Issue

The evaluations section does not show the role one had at an event. Preferably this is show on the evaluations overview so selection panels have quick access to the most relevant evaluations. It should then thereafter also be mentioned on the evaluation itself when clicking a specific evaluation. There is a difference in point of view regarding evaluations: the writer vs. the receiver. Preferably you should add both the roles from the writer and the receiver.

https://staging.members.eyp.org/user/lars-van-bourgognie/evaluations

**Comment by larsvanbourgognie** [comment]
There is a difference in point of view regarding evaluations: the writer vs. the receiver. Preferably you should add both the roles from the writer and the receiver.

**Comment by larsvanbourgognie** [comment]
#41

**Comment by ghost** [comment]
![Screenshot 2021-11-02 at 23 53 50](https://user-images.githubusercontent.com/91201200/139962841-9fab3fb0-90e9-492a-9eff-d2ccd56656f2.png)

Don't think the issue was made clear enough. Here, and in general for evaluations, it is rather irrelevant to know the position of the evaluator. (Though preferred to see both.) The **more important** thing is to have the role of the person that received an evaluation. In my case, the first evaluation written here by Nevena Ribic should mention that this was an evaluation for my role as President, next one as Head of Jury, etc.
