### ISSUE TITLE
Homepage dropdown menu "National Committees" not alphabetically ordered (apparently linked to "National committees" section)

### ISSUE THREAD

**Issue by ghost** [young-europe/Members-Platform-bug-reports#16]
Lars Van Bourgognie - 22/09/2021

Issue

The dropdown menu including all NCs is not alphabetically ordered. EYP Latvia is mentioned twice.

https://staging.members.eyp.org/home , applies to "National Committees" section as well

<img width="1280" alt="Screenshot 2021-09-22 at 3 28 34 PM" src="https://user-images.githubusercontent.com/91201200/134352902-e6e47637-c28f-4f47-8acd-3f54b7cebb45.png">

**Comment by larsvanbourgognie** [comment]
ADDITION: EYP Latvia is mentioned twice.

**Comment by mzibara** [comment]
@larsvanbourgognie Latvia appears twice due to the fact that somebody has added it repeatedly to the admin. We will check the ordering
