### ISSUE TITLE
Problems with adding new NC managers and editing session pages

### ISSUE THREAD

**Issue by anna3luglio** [young-europe/Members-Platform-bug-reports#166]
We encountered two problems:
1. President of the NC cannot add new NC managers because the new platform simply doesn't find them
2. NC managers cannot edit participants of session pages or the session page in general if they have not created the page. This has happened with regard to the following session pages:
RS Potenza (cannot edit participants)
RS Genova (cannot edit participants)
RS Trieste (cannot edit the event in general)
1. Normally we are able to add new NC managers 
2. NC managers can normally participants to the session page 

The following screenshot shows how the view should be for an NC manager
![WhatsApp Image 2021-11-11 at 16 14 13](https://user-images.githubusercontent.com/94124953/141323274-aa80f86f-6f2c-472e-862d-c1ca111bb815.jpeg)

**Comment by valboyko** [comment]
This now should be fixed - the search is performing better now. Please try again @anna3luglio
