### ISSUE TITLE
Database error - memory exhausted

### ISSUE THREAD

**Issue by anar868** [young-europe/Members-Platform-bug-reports#3]
Anar Mammadov - 22.09.2021
Bug
An error message (mentioned below) appears when trying to check open calls:
Error: {"graphQLErrors":[{"message":"PG::SyntaxError: ERROR: memory exhausted at or near \"\"open_call_id\"\"\nLINE 1: ...0e263b-8d86-4f98-bb91-aa11a1df54b6' AND \"entries\".\"open_call...\n ^\n","locations":[{"line":2,"column":3}],"path":["currentUserOpenCallEntry"]}],"clientErrors":[],"networkError":null,"message":"PG::SyntaxError: ERROR: memory exhausted at or near \"\"open_call_id\"\"\nLINE 1: ...0e263b-8d86-4f98-bb91-aa11a1df54b6' AND \"entries\".\"open_call...\n ^\n"}

URL: https://staging.members.eyp.org/events/fusion-2nd-digital-outreach-session-2021/open_calls/d1f349ca-5552-4f4b-9375-43a4c1c92ee4

![image](https://user-images.githubusercontent.com/55332837/134323248-664a40f3-f96d-4b5c-949d-3da33b1e79a2.png)

**Comment by alimaeve** [comment]
Ali-Maeve - 22.09.2021
Same error occurs for all open calls (ex. Members Training of EYP Ireland)
(see Ali-Maeve 22.09 05)
https://drive.google.com/file/d/1LszP1B5B2V60q4EURsxZrriDkkUn7X5H/view?usp=sharing
