### ISSUE TITLE
[BUG]-Special characters are accepted on SignUp 

### ISSUE THREAD

**Issue by BYllka** [young-europe/Members-Platform-bug-reports#32]
**REPORTER** : Yllka Berisha Mehmeti
**DATE** : 23.09.2021

**STEPS TO REPRODUCE**

1. Access https://staging.members.eyp.org/auth/sign_up
2. Enter an email with other special characters like #, $, &, * etc
3. Enter password and confirmation of password correctly
4. Accept terms and conditions
5. Check recaptcha
6. Sign up

**EXPECTED BEHAVIOR** Platform should show an error as 'Email is incorrect'
**ACTUAL BEHAVIOR**  Platform does not have backend validation and its accepting special characters 
**ACCEPTANCE CRITERIA** Valid special characters for email text box should be: dash, underline, at, dot ( **-**  **_**  **@**  **.** )
**VIDEO REFERENCE** [Please refer here](https://streamable.com/8vr266)

**Comment by mzibara** [comment]
![image](https://user-images.githubusercontent.com/17460019/138588998-8e35a19f-1f1b-4b92-aa11-67c495745be2.png)
