### ISSUE TITLE
Saturday 25th - not working

### ISSUE THREAD

**Issue by jamesris** [young-europe/Members-Platform-bug-reports#40]
Théophane Gauthier
Saturday 25th 2021 - 15:00 CEST
Website not working 
![image](https://user-images.githubusercontent.com/91188477/134772498-58bd7707-28c2-491f-81aa-15d083624bb5.png)

**Comment by daniel-buna** [comment]
Same for me!

**Comment by MaximeZingraff** [comment]
+1

**Comment by alimaeve** [comment]
Ali-Maeve :
Me too! I tried to refresh an old tab with a window of the new Member's Platform (that I'd opened on Thursday): and my entire computer crashed and had to be restarted (this hasnt happened to me ever before with this computer)

**Comment by pantsatdancing** [comment]
Still not functional as of timestamp

**Comment by alimaeve** [comment]
As of timestap: working again
