### ISSUE TITLE
Suggestion: Roles shown on My Evaluations

### ISSUE THREAD

**Issue by daniel-buna** [young-europe/Members-Platform-bug-reports#41]
Daniel Buna - 26/09/2021

On My Evaluations page, the roles shown in the list show that of the evaluator rather than the position you were evaluated for. I think it would be more beneficial to show the latter, seeing as displaying the role of the person evaluating there might be confusing and rarely makes a difference knowing what was their role. 

[https://staging.members.eyp.org/evaluations/index/my_evaluations]
<img width="1440" alt="Screen Shot 2021-09-26 at 11 14 19 AM" src="https://user-images.githubusercontent.com/80420820/134801647-c92b4d88-2238-46a4-a84a-04b5d5a24a6b.png">

**Comment by ghost** [comment]
#15
