### ISSUE TITLE
Poor searching filter

### ISSUE THREAD

**Issue by anar868** [young-europe/Members-Platform-bug-reports#43]
Anar Mammadov - 27.09.2021
Issue
Instead of showing the person with the exact name as searched, results show random people that has similar names with the search input. For example, when searching for "anar mammadov", "ali mammadov" comes first.
URL: https://staging.members.eyp.org/search_results/users
![image](https://user-images.githubusercontent.com/55332837/134831112-7cf9b621-1bb8-434c-9d54-ae342e9d8370.png)

**Comment by mzibara** [comment]
![image](https://user-images.githubusercontent.com/17460019/145782294-2128f792-2102-4485-b785-16e10792189e.png)
