### ISSUE TITLE
[BUG] Can't change password with account settings

### ISSUE THREAD

**Issue by DavidCapek** [young-europe/Members-Platform-bug-reports#48]
REPORTER: David Čapek
DATE: 27.09.2021
After opening the account settings (https://staging.members.eyp.org/my_profile) I tried to change the password by filling in the new and old password nevertheless I wasn't able to submit the changes. 

EXPECTED BEHAVIOR Platform should change the password after clicking the submit button or a dedicated button for the purpose.
ACTUAL BEHAVIOR Can not change the password, because the submit button is greyed out.

**Comment by mzibara** [comment]
@DavidCapek it looks like profile was not complete - some compulsory fields missing - therefore they were marked in red and password change could not be performed
