### ISSUE TITLE
[BUG] Wrong profile picture

### ISSUE THREAD

**Issue by DavidCapek** [young-europe/Members-Platform-bug-reports#52]
REPORTER: David Čapek
DATE: 27.09.2021

STEPS TO REPRODUCE

1. Open [https://staging.members.eyp.org/user/martin-simacek](https://staging.members.eyp.org/user/martin-simacek)
2. Open [https://members.eyp.org/users/martin-simacek](https://members.eyp.org/users/martin-simacek)
3. Compare two profile pictures

EXPECTED BEHAVIOR Profile pictures should be the same
ACTUAL BEHAVIOR Profile pictures aren't the same
ACCEPTANCE CRITERIA Profile pictures have to be the same

**Comment by ferdi-mayrhofer** [comment]
Ferdinand Mayrhofer
30/9/2021

It seems there is a general issue with pictures, as the picture of Yannick seems to be used for other users.
Example: Amelia Navarre
Old Platform: https://members.eyp.org/users/amelia-navarre (her picture)
New Platform: https://staging.members.eyp.org/user/amelia-navarre/events (Picture of Yannick Léonard)

Edit: The name of the file of the picture was "me.jpg"

![grafik](https://user-images.githubusercontent.com/91188368/135449463-c4ad4bef-65b2-4d3b-bcab-41b6f6194dce.png)
