### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by pantsatdancing** [young-europe/Members-Platform-bug-reports#54]
James Bullen - 28/09/21

Issue

Image is self explanatory.

https://staging.members.eyp.org/home

![image](https://user-images.githubusercontent.com/68863930/135174374-1f469bcd-5416-42fa-a1da-1d19ab7c455f.png)

**Comment by pantsatdancing** [comment]
Disregard. Just needed to refresh the page. 👀

**Comment by ferdi-mayrhofer** [comment]
Ferdinand Mayrhofer
30/9/2021

Having the same error with two users.
These are both newly created test-users ("testplatform@eyp.at" & "tina@eyp.at") for the new platform. They are both added as NC admin and added to one past event (as Head-Trainer or Head of Jury).
This error is happening on the main screen/home-tab (https://staging.members.eyp.org/home) and the events-tab (https://staging.members.eyp.org/events/index).
Neither page refresh nor logout and login does solve the issue.

Neither having these issues with a 2nd (unprivileged) test user nor my main account.
![grafik](https://user-images.githubusercontent.com/91188368/135490516-b3b93bd7-7001-4e51-a88b-25cabfeba40f.png)

**Comment by mzibara** [comment]
@pantsatdancing should be fixed now
