### ISSUE TITLE
server issue- event not found 

### ISSUE THREAD

**Issue by enislalmi** [young-europe/Members-Platform-bug-reports#60]
https://staging.members.eyp.org/events/eyp-school-kunzelsau  
![image](https://user-images.githubusercontent.com/68543019/135339640-c42fd9d2-6dc9-46bc-a564-3120aea111f2.png)
![image](https://user-images.githubusercontent.com/68543019/135339658-ce1e7763-356b-4e25-b662-007ff8f1d6ab.png)

**Comment by mzibara** [comment]
Dublicate of https://github.com/young-europe/Members-Platform-bug-reports/issues/71
