### ISSUE TITLE
you can submit a blank application

### ISSUE THREAD

**Issue by enislalmi** [young-europe/Members-Platform-bug-reports#62]
https://staging.members.eyp.org/events/tbilisi-city-session-2021-of-eyp-georgia/open_calls/81124885-6932-46c6-9d5f-c7262cfe924d  
![image](https://user-images.githubusercontent.com/68543019/135339961-c6ff5ad8-e44f-49d5-9ce4-9ee88819445e.png)

**Comment by mzibara** [comment]
@enislalmi this application has no validation regarding length or anything. What is the expected behavior?
