### ISSUE TITLE
[BUG] The redirect from /searchresults to /posts and vice versa is incorrect

### ISSUE THREAD

**Issue by BYllka** [young-europe/Members-Platform-bug-reports#64]
**REPORTER** : Yllka Berisha Mehmeti
**DATE** : 30.09.2021

**STEPS TO REPRODUCE**

1) Access https://staging.members.eyp.org/posts
2) There are 995 posts available
3) Search with unrelated keyword with posts (f.e. 'Berisha')
4) No search results show
5) Delete the keyword on search bar field
6) No posts show again

**EXPECTED BEHAVIOR** Platform should show again all the posts after erasing the keyword on search filter
**ACTUAL BEHAVIOR** Platform does not show anything after erasing the keyword. It remains in same directory of /searchresults
**ACCEPTANCE CRITERIA** The user should be able to see the results within the /posts directory. Separating directories makes it difficult to go back to previous action (view all posts). 
**VIDEO REFERENCE** Please refer[ here](https://streamable.com/91w1qz)

**Comment by mzibara** [comment]
@BYllka would disagree with the proposed flow. Search input is a shortcut to the search component, therefore after initial search you will be redirected to the search component, and continue operating there
