### ISSUE TITLE
[BUG] Users can fully use the platform without setting a name/filling in profile details

### ISSUE THREAD

**Issue by ferdi-mayrhofer** [young-europe/Members-Platform-bug-reports#66]
Ferdinand Mayrhofer
30/9/2021

I've created a new user (was then automatically logged in without verification - see the previous bug), and could then use the platform without setting a name in the settings page.
Via the email address, a user without a name can even be added as NC Board member (see screenshot).

Proposed solution: After the email-verification (previous bug), the user should be forced to first fill in the mandatory fields (first name, last name, nationality) in "My Profile" before the account can be used.
![user without name](https://user-images.githubusercontent.com/91188368/135448729-252208dc-74bd-4891-9f85-d92b4d3feaf9.JPG)

**Comment by mzibara** [comment]
@ferdi-mayrhofer we will validate user first_name and last_name on sign-up
![image](https://user-images.githubusercontent.com/17460019/138439851-68ba1cf9-f65e-41b5-9556-30adca7a340e.png)
