### ISSUE TITLE
[BUG] Published calls can't be edited - multiple calls with same position can be open

### ISSUE THREAD

**Issue by ferdi-mayrhofer** [young-europe/Members-Platform-bug-reports#68]
Ferdinand Mayrhofer
30/9/2021

Admin Panel for editing event:
Once a call is published, it can't be edited. Additionally, multiple calls for one position can be opened, which are also open simultaneously. Users can also apply using both forms.
1. Once a call for a position is open, it should not be possible that there are multiple simultaneous calls for the identical position.
2. It should be possible to edit calls.

Example Event: https://staging.members.eyp.org/admin/events/eyp-austria-members-weekend-2021
![grafik](https://user-images.githubusercontent.com/91188368/135451379-d2b698ac-fe54-4d7c-80af-3563a3da85d3.png)

**Comment by EYP-HR-Liam** [comment]
It will be possible to have multiple calls but it will also be possible to change open calls. This is to allow for calls to be reopened in the case of dropouts or changing dates.
