### ISSUE TITLE
American English Spellings

### ISSUE THREAD

**Issue by alimaeve** [young-europe/Members-Platform-bug-reports#7]
Ali-Maeve - 22.09.2021
Minor Issue
Event role 'Organiser' uses American English spelling 'Organizer', while working language of EYP is British English
(see Ali-Maeve 22.09 02)
https://drive.google.com/file/d/1EKyAICUETNDVIj2FbuzPkJnGVKdycY_H/view?usp=sharing

**Comment by en11s** [comment]
In the dropdown menu of events there are some misspelled event types

**Comment by aliokm** [comment]
+ Head Organiser is abbreviated as HO. Not sure if this is intentional but would probably make sense to have abbreviated role names
