### ISSUE TITLE
[Error] We're sorry, but something went wrong (500) - when trying to edit a SSEE

### ISSUE THREAD

**Issue by ferdi-mayrhofer** [young-europe/Members-Platform-bug-reports#71]
Ferdinand Mayrhofer
30/9/2021

When trying to edit the Event "EYP Austria Online Mini Session", an error message showed up.
https://staging.members.eyp.org/admin/events/eyp-austria-online-mini-session/edit, a Small-Scale EYP Event 

> Error: {"graphQLErrors":[],"clientErrors":[],"networkError":{"name":"ServerParseError","response":{},"statusCode":500,"bodyText":"<!DOCTYPE html>\n<html>\n<head>\n <title>We're sorry, but something went wrong (500)</title>\n <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n <style>\n .rails-default-error-page {\n background-color: #EFEFEF;\n color: #2E2F30;\n text-align: center;\n font-family: arial, sans-serif;\n margin: 0;\n }\n\n .rails-default-error-page div.dialog {\n width: 95%;\n max-width: 33em;\n margin: 4em auto 0;\n }\n\n .rails-default-error-page div.dialog > div {\n border: 1px solid #CCC;\n border-right-color: #999;\n border-left-color: #999;\n border-bottom-color: #BBB;\n border-top: #B00100 solid 4px;\n border-top-left-radius: 9px;\n border-top-right-radius: 9px;\n background-color: white;\n padding: 7px 12% 0;\n box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);\n }\n\n .rails-default-error-page h1 {\n font-size: 100%;\n color: #730E15;\n line-height: 1.5em;\n }\n\n .rails-default-error-page div.dialog > p {\n margin: 0 0 1em;\n padding: 1em;\n background-color: #F7F7F7;\n border: 1px solid #CCC;\n border-right-color: #999;\n border-left-color: #999;\n border-bottom-color: #999;\n border-bottom-left-radius: 4px;\n border-bottom-right-radius: 4px;\n border-top-color: #DADADA;\n color: #666;\n box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);\n }\n </style>\n</head>\n\n<body class=\"rails-default-error-page\">\n \n <div class=\"dialog\">\n <div>\n <h1>We're sorry, but something went wrong.</h1>\n </div>\n <p>If you are the application owner check the logs for more information.</p>\n </div>\n</body>\n</html>\n"},"message":"JSON.parse: unexpected character at line 1 column 1 of the JSON data"}

![grafik](https://user-images.githubusercontent.com/91188368/135488352-ad69f9db-4832-4fb0-a7ef-4f08c33cc9e0.png)

**Comment by mzibara** [comment]
@ferdi-mayrhofer database error on old members platform, event was created with kind "smallscale_ey_pevent" (typo). We have added validation, that would filter out such issue on migration
