### ISSUE TITLE
Reset password token is invalid

### ISSUE THREAD

**Issue by MariiaKurova** [young-europe/Members-Platform-bug-reports#74]
Mariia Kurova, 1.10.2021
While reseting the password for the used-on-the-previous-platform mail the form to reset the password by link is given, however after entering several variants of passwords on the several browsers (Firefox, Chrome, Opera) it gives the same issue: reset password token is invalid. [https://drive.google.com/file/d/1mITgXiQ0gErGKR6sP4vyOetDe2A-B-hi/view?usp=sharing](url) [https://drive.google.com/file/d/10dnEml0FhC6_3e043bSUn_Vbx6d9ZL_5/view?usp=sharing](url)

**Comment by MariiaKurova** [comment]
> 
> 
> Mariia Kurova, 1.10.2021 While reseting the password for the used-on-the-previous-platform mail the form to reset the password by link is given, however after entering several variants of passwords on the several browsers (Firefox, Chrome, Opera) it gives the same issue: reset password token is invalid. [https://drive.google.com/file/d/1mITgXiQ0gErGKR6sP4vyOetDe2A-B-hi/view?usp=sharing](url) [https://drive.google.com/file/d/10dnEml0FhC6_3e043bSUn_Vbx6d9ZL_5/view?usp=sharing](url)

Mariia Kurova, 1.10.2021
The new update of the issue of reseting the password:
as I resently tried to follow the same link from the same gmail I used on the previous platform I got an unexpected result in a form of sending me to another profile's home page, recently signed up using another gmail instead of the previous reseting the password form. [https://drive.google.com/file/d/1gWZRc7EGPvnBlonLFe_2cAwLBfZ5we7D/view?usp=sharing](url) [https://drive.google.com/file/d/1T9_zMeMGMmgH7gos1kJbstIm4M3vVPmQ/view?usp=sharing](url)

**Comment by mzibara** [comment]
@MariiaKurova please check that the reset link is copied in whole, so the reset token matches.

**Comment by MariiaKurova** [comment]
staging.members.eyp.org/auth/password
