### ISSUE TITLE
No restrictions on word count in applications

### ISSUE THREAD

**Issue by kolbascka** [young-europe/Members-Platform-bug-reports#76]
Ekaterina Ignashova - 03/10/21

Issue

When applying for any position at a session (via clicking on the "Open Calls"), there are no restrictions on how many words you can write, even in fields that specify for example "max. 100 words". Suggestion - either include a word count at the bottom of the entry field, or disallow the user from typing any more words after they reach the limit for that field. Or, if the word limits are just a guide, specify that they aren't strict and will not influence the outcome of your application (e.g., something like "approx. 100 words" instead of "max. 100 words").

See first image for me entering more than 100 words in a "max. 100 words" field. See the second image for the fact that the application proceeds as successful, even despite this.
![bug01](https://user-images.githubusercontent.com/53514906/135757597-9f98eacd-eebc-4b50-8e7a-23bff8a53edf.PNG)
![bug_02](https://user-images.githubusercontent.com/53514906/135757604-d5d23533-f156-4c56-803c-e818a46679b6.PNG)

**Comment by mzibara** [comment]
![image](https://user-images.githubusercontent.com/17460019/138431306-f51e608a-8cd6-4074-a0c2-36f7fd9956c7.png)

Words have been replaced with characters and proper validation is performed
