### ISSUE TITLE
Profile - # Events Incorrect

### ISSUE THREAD

**Issue by alimaeve** [young-europe/Members-Platform-bug-reports#8]
Ali-Maeve - 22.09.2021
Bug
In own profile; attended events reads '27', when counting number of events is actually 30 (from both old & new Members Platforms- no events missing on new platform; just miscalculated)
(see Ali-Maeve 22.09 03)
https://drive.google.com/file/d/1lZaKrHYj80Gt_1sqPbpl-CIwjGeqJle_/view?usp=sharing

**Comment by daniel-buna** [comment]
I think it counts sessions that have already happened, and not new ones (upcoming).

**Comment by mzibara** [comment]
@alimaeve confirm. Attended event count displays happened events
