### ISSUE TITLE
[Filter BUG] - Event filter bugs out with dates

### ISSUE THREAD

**Issue by aliokm** [young-europe/Members-Platform-bug-reports#80]
Ali Okumusoglu - 03/10

The event filter on the home page bugs out if a date range larger than a few weeks is selected. I've not figured out the length exactly but if October 2017-October 2021 is selected, the filter will not show anything. If August 21-October 21 is selected, it only shows T4ET? 

**Additional suggestion:** The date range should perhaps start with the earliest session on the Members Platform, with the upper range being no higher than the current year. 

https://www.dropbox.com/s/zbns20q3ec6qtjl/Bug3.png?dl=0
https://www.dropbox.com/s/yc73knkj5q0vdw5/Bug%203.1.png?dl=0

**Comment by mzibara** [comment]
@aliokm filter works as expected.
Home page only shows future events, therefore we are not expecting older events to show up

![image](https://user-images.githubusercontent.com/17460019/138411356-0fc2aa38-3eb4-4ebc-a137-02fb2584972c.png)
