### ISSUE TITLE
[BUG] Search function

### ISSUE THREAD

**Issue by aliokm** [young-europe/Members-Platform-bug-reports#82]
Ali Okumusoglu - 03/10

The search function for events doesn't always work? Sometimes it gives 'no results found' and sometimes it shows results if I refresh. Overall, it simply doesn't work with a lot of queries that it should otherwise be able to find.

<img width="576" alt="Screenshot 2021-10-03 at 17 43 28" src="https://user-images.githubusercontent.com/91838353/135761420-b8a08369-1d49-4438-a17e-572a388686d5.png">

I specifically get this issue if I searched for something and did not get results, then search something that I would otherwise get results for but then don't. 

For example: 
1. I search 'Minsk' and I get some results 
2. I search 'Minsk 2017' - get no results
3. I search 'Minsk' again and get no results - even if I refresh the page. 
4. 'Minsk' is typed into the search box no matter how many times I refresh or go to other pages - and it keeps saying 'no results found'

**Comment by ferdi-mayrhofer** [comment]
Seems similar to the issues I experienced when adding people to NCs; see issue #69.
A full refresh of the page ("Control + F5" on Windows) seems to make it work again.

However, when trying your "Minsk (2017)" example from above, I always get results.
